<?php
require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../config/config.php';

// Validate user_id
$id = isset($_GET['user_id']) ? intval($_GET['user_id']) : 0;
if (!$id) {
    die('Invalid user ID');
}

// Get transaction type
$type = $_GET['type'] ?? 'all';
$typeMap = [
    'all' => '',
    'deposit' => 'deposit',
    'withdrawal' => 'withdrawal',
    'transfer' => 'transfer',
    'credit' => 'credit',
];
$transactionType = $typeMap[$type] ?? '';

try {
    $db = getDB();
    
    // Get user info
    $user = $db->fetchOne("SELECT * FROM users WHERE id = ?", [$id]);
    if (!$user) {
        die('User not found');
    }

    // Build query
    $where = ['user_id = ?'];
    $params = [$id];
    if ($transactionType) {
        $where[] = 'type = ?';
        $params[] = $transactionType;
    }
    $whereSql = 'WHERE ' . implode(' AND ', $where);
    
    // Get transactions
    $transactions = $db->fetchAll("
        SELECT * FROM transactions 
        $whereSql 
        ORDER BY created_at DESC
    ", $params);

} catch (Exception $e) {
    error_log('Print error: ' . $e->getMessage());
    die('Error loading transactions. Please try again later.');
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Transaction Report - <?= htmlspecialchars($user['name']) ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        @media print {
            @page { size: landscape; }
            body { 
                padding: 20px;
                font-size: 12px;
            }
            .table th { 
                background-color: #00572d !important;
                color: white !important;
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }
            .badge {
                border: 1px solid #333;
            }
            .no-print { display: none !important; }
        }
        .table th { 
            background-color: #00572d;
            color: white;
        }
    </style>
</head>
<body>
    <div class="container-fluid">
        <div class="d-flex justify-content-between align-items-center mb-4">
            <div>
                <h4 style="color:#00572d;">Transaction Report</h4>
                <div class="text-muted">
                    <strong>User:</strong> <?= htmlspecialchars($user['name']) ?> (<?= htmlspecialchars($user['email']) ?>)<br>
                    <strong>Department:</strong> <?= htmlspecialchars($user['department']) ?><br>
                    <strong>Type:</strong> <?= ucfirst($type) ?> Transactions<br>
                    <strong>Generated:</strong> <?= date('Y-m-d H:i:s') ?>
                </div>
            </div>
            <button onclick="window.print()" class="btn btn-primary no-print">
                <i class="fas fa-print"></i> Print
            </button>
        </div>

        <table class="table table-bordered table-sm">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Type</th>
                    <th>Amount</th>
                    <th>Status</th>
                    <th>Reference</th>
                    <th>Description</th>
                    <th>Created</th>
                </tr>
            </thead>
            <tbody>
                <?php if ($transactions): ?>
                    <?php foreach ($transactions as $tx): ?>
                    <tr>
                        <td><?= $tx['id'] ?></td>
                        <td><?= ucfirst($tx['type'] ?? '') ?></td>
                        <td>₦<?= number_format($tx['amount'] ?? 0, 2) ?></td>
                        <td>
                            <span class="badge <?= $tx['status']==='approved'?'bg-success':($tx['status']==='pending'?'bg-warning text-dark':'bg-danger') ?>">
                                <?= ucfirst($tx['status'] ?? '') ?>
                            </span>
                        </td>
                        <td><?= htmlspecialchars($tx['reference'] ?? '') ?></td>
                        <td><?= htmlspecialchars($tx['description'] ?? '') ?></td>
                        <td><?= htmlspecialchars(date('Y-m-d H:i', strtotime($tx['created_at'] ?? ''))) ?></td>
                    </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <td colspan="7" class="text-center">No transactions found.</td>
                    </tr>
                <?php endif; ?>
            </tbody>
        </table>

        <div class="text-muted small mt-4">
            <p>Generated by DUTSCA Financial System</p>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/your-font-awesome-kit.js"></script>
</body>
</html> 